# Generated by Django 4.1.7 on 2023-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_user_delete_message_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(max_length=25, unique=True),
        ),
    ]
